/*
 * funciones.h
 *
 *  Created on: 16 abr. 2021
 *      Author: agust
 */

#ifndef FUNCIONES_H_
#define FUNCIONES_H_
#include <stdio.h>
#include <ctype.h>
#define T 10
#define entero 1
#define cero 0
#define decimal 2
#define negativo -1

void MostrarMenu(void); //ESTA FUNCION SE ENCARGA DE MOSTRAR EL MENU DE OPCIONES.
int ValidarOpcion(int,int); //ESTA FUNCION SE ENCARGA DE VALIDAR QUE LA OPCION INGRESADA ESTE DENTRO DE UN RANGO DE NUMEROS. DEVUELVE LA OPCION VALIDADA COMO UN NUMERO ENTERO.
int SumarEnteros(int, int); //ESTA FUNCION SE ENCARGA DE SUMAR DOS NUMEROS ENTEROS. DEVUELVE EL RESULTADO COMO UN NUMERO ENTERO.
float SumarFlotantes(float,float); //ESTA FUNCION SE ENCARGA DE SUMAR DOS NUMEROS FLOTANTES. DEVUELVE EL RESULTADO COMO UN NUMERO FLOTANTE.
float SumarEnteroFlotante(int,float); //ESTA FUNCION SE ENCARGA DE SUMAR UN NUMERO ENTERO Y UNO FLOTANTE. DEVUELVE EL RESULTADO COMO UN NUMERO FLOTANTE.

int RestarEnteros(int,int); //ESTA FUNCION SE ENCARGA DE RESTAR DOS NUMEROS ENTEROS. DEVUELVE EL RESULTADO COMO UN NUMERO ENTERO.
float RestarFlotantes(float,float); //ESTA FUNCION SE ENCARGA DE RESTAR DOS NUMEROS FLOTANTES. DEVUELVE EL RESULTADO COMO UN NUMERO FLOTANTE.
float RestarEnteroFlotante(int,float); //ESTA FUNCION SE ENCARGA DE RESTARLE UN NUMERO FLOTANTE A UN NUMERO ENTERO. DEVUELVE EL RESULTADO COMO UN NUMERO FLOTANTE.
float RestarFlotanteEntero(float,int); //ESTA FUNCION SE ENCARGA DE RESTARLE UN NUMERO ENTERO A UN NUMERO FLOTANTE. DEVUELVE EL RESULTADO COMO UN NUMERO FLOTANTE.

float DividirEnteros(int,int); //ESTA FUNCION SE ENCARGA DE DIVIDIR DOS NUMEROS ENTEROS ENTRE SI. DEVUELVE EL RESULTADO COMO UN NUMERO FLOTANTE.
float DividirFlotantes(float,float); //ESTA FUNCION SE ENCARGA DE DIVIDIR DOS NUMERO FLOTANTES ENTRE SI. DEVUELVE EL RESULTADO COMO UN NUMERO FLOTANTE.
float DividirEnteroFlotante(int,float); //ESTA FUNCION SE ENCARGA DE DIVIDIR UN NUMERO ENTERO POR UN NUMERO FLOTANTE. DEVUELVE EL RESULTADO COMO UN NUMERO FLOTANTE.
float DividirFlotanteEntero(float,int); //ESTA FUNCION SE ENCARGA DE DIVIDIR UN NUMERO FLOTANTE POR UN NUMERO ENTERO. DEVUELVE EL RESULTADO COMO UN NUMERO FLOTANTE.

int MultiplicarEnteros(int,int); //ESTA FUNCION SE ENCARGA DE MULTIPLICAR DOS NUMEROS ENTEROS ENTRE SI. DEVUELVE EL RESULTADO COMO UN NUMERO ENTERO.
float MultiplicarFlotantes(float,float); //ESTA FUNCION SE ENCARGA DE MULTIPLICAR DOS NUMEROS FLOTANTES ENTRE SI. DEVUELVE EL RESULTADO COMO UN NUMERO FLOTANTE.
float MultiplicarEnteroFlotante(int,float); //ESTA FUNCION SE ENCARGA DE MULTIPLICAR UN NUMERO ENTERO POR UN FLOTANTE. DEVUELVE EL RESULTADO COMO UN NUMERO FLOTANTE.

int FactorizarNumeros(int); //ESTA FUNCION SE ENCARGA DE FACTORIZAR UN NUMERO ENTERO. DEVUELVE EL RESULTADO COMO UN NUMERO ENTERO.

#endif /* FUNCIONES_H_ */
